### PR TITLE
Add http-only stack test, Add results after JIT, Add Aleph Http Server

### PR DESCRIPTION
**Pull request by alexpetrov**

### CODE REVIEW

**Comment by alexpetrov** [comment]
As I said, after JIT compilation, Clojure server is always 25% faster than Rails. But I was expected bigger difference. For http-stack only, difference is 50%.
I would suggest to optimize Rails app for API by removing all unnecessary middlewares. Some information is [here](https://github.com/rails-api/rails-api) . I have not read it yet, but hear about it in podcasts.
Also we should definitely add [Roda](https://github.com/jeremyevans/roda) implementation to comparisson. Seems like it is the fastest microframework today.

Thank you for interesting benchmark project! It was joyful to play with!

**Comment by exAspArk** [comment]
@alexpetrov thank you so much for the pull request and tips about optimizing performance! :tada: 

I have also pushed benchmarks I run on my laptop to [master](https://github.com/exAspArk/rails_compojure/blob/master/README.md). Seems like your Compojure app becomes much faster after warming JVM up than mine (about 30% :rocket:). Have you tuned your JVM? :)

**Comment by alexpetrov** [comment]
You are welcome, @exAspArk !
I am not sure If I tuned my JVM somehow. But may be it make sense, that I have JVM optimized for Server side. Therefore it spends more time to gather statistics about hot points in the code and optimizes better than client one. Here is my java version:

```
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

By the way, I am very surprized with your results. I have to think about it.
@exAspArk , show me, please, your `java -version` output.

**Comment by exAspArk** [comment]
@alexpetrov,

```
> java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

I will try to run these benchmarks on my colleagues' laptops a bit later :)

**Comment by alexpetrov** [comment]
Interesting... Looking forward for results!
One more detail. I use Linux Mint 17.1 (Ubuntu based distro).

**Pull request merged**
